goodblog/blog/urls.py
from django.urls import path

from goodblog.urls import router
from . import views


router.register(r'blog/articles', views.PostViewSet)

app_name='blog'
urlpatterns = [
    path('new-post/', views.PostView.as_view(), name='new-post'),
    path('my-posts/', views.MyPostsView.as_view(), name='user-posts'),
    path('search/', views.SearchPostView.as_view(), name='search-post'),
    path('tag/<tag_name>', views.tag_posts, name='tag-posts'),
    path('article/<pk>/<slug:title>', views.PostDetail.as_view(), name='post-detail'),
    path('update-article/<pk>', views.PostUpdate.as_view(), name='post-update'),
    path('publish-article/<post_id>', views.publish_post, name='publish-post'),
    path('unpublish-article/<post_id>', views.unpublish_post, name='unpublish-post'),
]

goodblog/blog/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy
from django.template.defaultfilters import slugify

from tinymce.models import HTMLField
from taggit.managers import TaggableManager


class UserProfile(models.Model):
    USER_LEVEL_OPTIONS = [
        (1, 'Administrator'),
        (2, 'Author'),
        (3, 'Reader'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE, editable=False)
    level = models.SmallIntegerField(choices=USER_LEVEL_OPTIONS, default=3)

    def __str__(self):
        return str(self.level)


class Post(models.Model):
    title = models.CharField(max_length=255, unique=True)
    create_date = models.DateTimeField(auto_now_add=True)
    publish_date = models.DateTimeField(null=True, blank=True, help_text="yyyy-mm-dd hh:mm:ss")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = TaggableManager()
    content = HTMLField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('blog:post-detail', args=[self.id, slugify(self.title)])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    publish_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = HTMLField()

    def __str__(self):
        return self.publish_date.strftime("%d %B %Y, %H:%M")

goodblog/blog/forms.py
from django import forms

from tinymce.widgets import TinyMCE

from . import models


class PostForm(forms.ModelForm):
    id = forms.CharField(widget=forms.HiddenInput(), disabled=True, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tags'].widget.attrs.update({'class': 'input'})

    class Meta:
        model = models.Post
        fields = ['id', 'title', 'tags', 'publish_date', 'content']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'input'}),
            'publish_date': forms.TextInput(attrs={'class': 'input'}),
            'content': TinyMCE()
        }


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['content'].widget.attrs.update({'class': 'textarea is-info is-small'})

    class Meta:
        model = models.Comment
        fields = ['content']

goodblog/blog/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils import timezone
from django.utils.text import slugify
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.postgres.search import SearchVector
from django.shortcuts import get_object_or_404
from django.http import Http404

from rest_framework import viewsets, permissions, renderers
from taggit.models import Tag

from . import models, forms, serializers
from .permissions import IsOwnerOrReadOnly


class TestPostAuthor(UserPassesTestMixin):
    def test_func(self):
        return bool(self.request.user.userprofile.level < 3)


class PostDetail(DetailView):
    model = models.Post
    template_name = 'blog/post-detail.html'
    pk_url_kwarg = 'pk'
    slug_url_kwarg = 'title'

    def get_object(self, *args, **kwargs):
        this_post = super(PostDetail, self).get_object(*args, **kwargs)
        if this_post.publish_date is None or this_post.publish_date > timezone.now():
            if this_post.author != self.request.user:
                raise Http404

            return this_post
        else:
            return this_post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['comment_form'] = forms.CommentForm()
        context['comments'] = models.Comment.objects.filter(
                post=self.get_object()).order_by('-publish_date')
        context['tags'] = Tag.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        comment_form = forms.CommentForm(self.request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = self.get_object()
            comment.author = self.request.user
            comment.save()
            return redirect(reverse_lazy('blog:post-detail',
                args=[self.get_object().id, slugify(self.get_object().title)]))
        else:
            return self.get(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class PostUpdate(TestPostAuthor, UpdateView):
    model = models.Post
    template_name = 'blog/post-update.html'
    form_class = forms.PostForm

    def get_success_url(self):
        return reverse_lazy('blog:post-detail', args=[self.object.id, slugify(self.object.title)])


@method_decorator(login_required, name='dispatch')
class PostView(TestPostAuthor, CreateView):
    model = models.Post
    template_name = "blog/new-post.html"
    form_class = forms.PostForm

    def get_success_url(self, *args, **kwargs):
        return reverse_lazy('blog:post-detail', args=[self.object.id, slugify(self.object.title)])


    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class MyPostsView(TestPostAuthor, ListView):
    model = models.Post
    template_name = "blog/my-posts.html"

    def get_queryset(self):
        return super().get_queryset().filter(author=self.request.user).order_by('-publish_date')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['time_now'] = timezone.now()
        return context


@login_required
def publish_post(request, post_id):
    post = get_object_or_404(models.Post, pk=post_id)
    post.publish_date = timezone.now()
    post.save()
    return redirect('blog:user-posts')


@login_required
def unpublish_post(request, post_id):
    post = get_object_or_404(models.Post, pk=post_id)
    post.publish_date = None
    post.save()
    return redirect('blog:user-posts')


class SearchPostView(ListView):
    model = models.Post
    template_name = 'blog/search-post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = self.model.objects.annotate(
                search=SearchVector('title', 'content'),
                ).filter(
                        publish_date__lte=timezone.now(), search=query
                ).select_related('author').prefetch_related('tags').order_by('-publish_date')
        return object_list


def tag_posts(request, tag_name):
    posts = models.Post.objects.filter(tags__name=tag_name)
    tags = Tag.objects.all()
    return render(request, 'blog/tag-posts.html',
            {
                'post_list': posts,
                'tags': tags,
            })


class PostViewSet(viewsets.ModelViewSet):
    queryset = models.Post.objects.all()
    serializer_class = serializers.PostSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

goodblog/blog/templates/blog/home.html
{% extends 'djcore/base.html' %}

{% block side_menu %}
{% include 'blog/post-side-menu.html' %}
{% endblock %}

{% block page_content %}
{% include 'blog/posts-list.html' %}
{% endblock %}

goodblog/blog/templates/blog/my-posts.html
{% extends "djcore/base.html" %}

{% block page_title %}Semua tulisanku{% endblock %}

{% block side_menu %}
{% include 'blog/side-menu/my-post-side-menu.html' %}
{% endblock %}

{% block page_content %}
<div class="content">
    <h1>Daftar Tulisan</h1>
    <table class="table is-bordered is-striped is-hoverable">
        <thead>
            <tr>
                <th>#</th>
                <th>Judul</th>
                <th>Status Publikasi</th>
                <th>Manajemen</th>
            </tr>
        </thead>
        <tbody>
            {% for post in object_list %}
            <tr class="{% cycle 'pure-table-odd' 'pure-table-even' %}">
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'blog:post-detail' post.id post.title|slugify %}">{{ post.title }}</a></td>
                <td>{{ post.publish_date }}</td>
                <td>
                    <a href="{% url 'blog:post-update' post.id %}">Edit</a>
                    {% if post.publish_date <= time_now %}
                    <a href="{% url 'blog:unpublish-post' post.id %}">Unpublish</a>
                    {% elif post.publish_date > time_now %}
                    <a href="{% url 'blog:publish-post' post.id %}">Publish Now</a>
                    {% else %}
                    <a href="{% url 'blog:publish-post' post.id %}">Publish</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

goodblog/blog/templates/blog/new-post.html
{% extends "djcore/base.html" %}

{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'blog/vendor/flatpickr/flatpickr.min.css' %}">
<link rel="stylesheet" href="{% static 'blog/vendor/flatpickr/plugins/confirmDate.css' %}">
{{ form.media }}
{% endblock %}

{% block side_menu %}
{% include 'blog/side-menu/my-post-side-menu.html' %}
{% endblock %}

{% block page_content %}
{% include 'blog/post-editor.html' %}
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'blog/vendor/flatpickr/flatpickr.min.js' %}"></script>
<script type="text/javascript" src="{% static 'blog/vendor/flatpickr/plugins/confirmDate.js' %}"></script>
<script type="text/javascript" src="{% static 'blog/js/blog.js' %}"></script>
{% endblock %}

goodblog/blog/templates/blog/post-detail.html
{% extends 'djcore/base.html' %}

{% block page_title %}{{ object.title }} | {{ block.super }}{% endblock %}

{% block side_menu %}
{% include 'blog/post-side-menu.html' %}
{% endblock %}

{% block page_content %}
<div class="content">
    <h1>{{ object.title }}</h1>
    <div>
        oleh {{ object.author }} pada {{ object.publish_date }}
        {% if post.author == request.user %}
        <a href="{% url 'blog:post-update' post.id %}">Edit</a>
        {% endif %}
    </div>
    
    {{ object.content|safe }}

    <h2>Komentar</h2>
        
    {% if comment_form %}
    <form method="POST">{% csrf_token %}
        {{ comment_form.as_p }}
        <button type="submit" class="button is-primary">Simpan komentar</button>
        <button type="reset" class="button is-warning">Hapus komentar</button>
    </form>
    {% endif %}

    {% for comment in comments %}
    <article class="media">
        <div class="media-content">
          <div class="content">
            <p>
              <strong>{{ comment.author }}</strong> <small>{{ comment.publish_date }}</small>
              <br>
              {{ comment.content }}
            </p>
          </div>
          <nav class="level is-mobile">
            <div class="level-left">
              <a class="level-item">
                <span class="icon is-small"><i class="fa fa-reply"></i></span>
              </a>
              <a class="level-item">
                <span class="icon is-small"><i class="fa fa-heart"></i></span>
              </a>
            </div>
          </nav>
        </div>
      </article>
    {% endfor %}
</div>
{% endblock %}

goodblog/blog/templates/blog/post-editor.html
<form id="post-form" method="POST">{% csrf_token %}
{{ form.id }}
{{ form.non_field_errors }}
<div class="field is-horizontal">
    <div class="field-label is-normal">
        <label class="label" for="{{ form.title.id_for_label }}">Title</label>
    </div>
    <div class="field-body">
        <div class="field">
            <div class="control">
                {{ form.title }}
            </div>
            {{ form.title.errors }}
        </div>
    </div>
</div>

<div class="field is-horizontal">
    <div class="field-label is-normal">
        <label class="label" for="{{ form.tags.id_for_label }}">Tags</label>
    </div>
    <div class="field-body">
        <div class="field">
            <p class="control is-expanded has-icons-left">
            {{ form.tags }}
            <span class="icon is-small is-left">
                <i class="fa fa-tag"></i>
            </span>
            </p>
            {{ form.tags.errors }}
        </div>
    </div>
</div>

<div class="field is-horizontal">
    <div class="field-label is-normal">
        <label class="label" for="{{ form.publish_date.id_for_label }}">Publish Date</label>
    </div>
    <div class="field-body">
        <div class="field">
            <p class="control is-expanded has-icons-left">
            {{ form.publish_date }}
            <span class="icon is-small is-left">
                <i class="fa fa-calendar"></i>
            </span>
            </p>
            {{ form.publish_date.errors }}
        </div>
    </div>
</div>

<div class="field">
      <div class="control">
          {{ form.content }}
      </div>
</div>

<div class="field is-horizontal">
  <div class="field-body">
    <div class="field is-grouped is-grouped-right">
      <div class="control">
      <button type="submit" class="button is-primary">Simpan data</button>
      </div>
      <div class="control">
      <button type="reset" class="button is-warning">Hapus data</button>
      </div>
    </div>
  </div>
</div>
</form>

goodblog/blog/templates/blog/post-side-menu.html
<div class="tile is-ancestor is-vertical">
    <div class="tile is-child">
        <form method="GET" action="{% url 'blog:search-post' %}">
        <div class="field has-addons">
            <div class="control is-expanded">
                <input class="input" type="text" name="q"
                    placeholder="Cari tulisan"
                    value="{% if request.GET.q %}{{ request.GET.q }}{% endif %}">

            </div>
            <div class="control">
                <button class="button is-info" type="submit">Cari</a>
            </div>
        </div>
        </form>
    </div>
    <div class="tile is-child">
        <div class="dropdown is-hidden-desktop">
            <div class="dropdown-trigger">
                <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
                    <span>Label</span>
                    <span class="icon is-small">
                        <i class="fa fa-angle-down" aria-hidden="true"></i>
                    </span>
                </button>
            </div>
            <div class="dropdown-menu" id="dropdown-menu" role="menu">
                <div class="dropdown-content tags">
                    {% for tag in tags %}
                    <a href="{% url 'blog:tag-posts' tag.slug %}" class="dropdown-item tag">
                        {{ tag.name }}
                    </a>
                    {% endfor %}
                    </a>
                </div>
            </div>
        </div>

        <aside class="menu is-hidden-touch">
            <p class="menu-label">
                Label
            </p>
            <div class="menu-list tags">
                {% for tag in tags %}
                <a href="{% url 'blog:tag-posts' tag.slug %}">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </aside>
    </div>
</div>

goodblog/blog/templates/blog/post-update.html
{% extends "djcore/base.html" %}

{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'blog/vendor/flatpickr/flatpickr.min.css' %}">
<link rel="stylesheet" href="{% static 'blog/vendor/flatpickr/plugins/confirmDate.css' %}">
{{ form.media }}
{% endblock %}

{% block side_menu %}
{% include 'blog/side-menu/my-post-side-menu.html' %}
{% endblock %}

{% block page_content %}
{% include 'blog/post-editor.html' %}
{% endblock %}
{% block extra_js %}
<script type="text/javascript" src="{% static 'blog/vendor/flatpickr/flatpickr.min.js' %}"></script>
<script type="text/javascript" src="{% static 'blog/vendor/flatpickr/plugins/confirmDate.js' %}"></script>
<script type="text/javascript" src="{% static 'blog/js/blog.js' %}"></script>
{% endblock %}

goodblog/blog/templates/blog/posts-list.html
{% for post in post_list %}
<article class="message is-info">
    <div class="message-header">
        <p><a href="{% url 'blog:post-detail' post.id post.title|slugify %}">{{ post.title }}</a></p>
        <p class="tags">{% for tag in post.tags.all %}
        <a class="tag is-rounded" href="{% url 'blog:tag-posts' tag.slug %}">{{ tag }}</a>{% endfor %}</p>
    </div>
    <div class="message-body">
        <p>{{ post.publish_date }}</p>
        {{ post.content|safe|truncatewords_html:20 }}
    </div>
</article>
{% empty %}
<div class="content">
    <h1>Data tidak ditemukan</h1>
</div>
{% endfor %}

goodblog/blog/templates/blog/search-post.html
{% extends 'djcore/base.html' %}

{% block side_menu %}
{% include 'blog/post-side-menu.html' %}
{% endblock %}

{% block page_content %}
{% include 'blog/posts-list.html' %}
{% endblock %}

goodblog/blog/templates/blog/tag-posts.html
{% extends 'djcore/base.html' %}

{% block side_menu %}
{% include 'blog/post-side-menu.html' %}
{% endblock %}

{% block page_content %}
{% include 'blog/posts-list.html' %}
{% endblock %}