goodblog/blog/urls.py
from django.urls import path

from goodblog.urls import router
from . import views


router.register(r'blog/articles', views.PostViewSet)

app_name='blog'
urlpatterns = [
    path('new-post/', views.PostView.as_view(), name='new-post'),
    path('my-posts/', views.MyPostsView.as_view(), name='user-posts'),
    path('search/', views.SearchPostView.as_view(), name='search-post'),
    path('tag/<tag_name>', views.tag_posts, name='tag-posts'),
    path('article/<pk>/<slug:title>', views.PostDetail.as_view(), name='post-detail'),
    path('update-article/<pk>', views.PostUpdate.as_view(), name='post-update'),
    path('publish-article/<post_id>', views.publish_post, name='publish-post'),
    path('unpublish-article/<post_id>', views.unpublish_post, name='unpublish-post'),
]

goodblog/cashflow/urls.py
from django.urls import path

from goodblog.urls import router

from . import views

router.register(r'cashflow/transaction', views.TransactionViewSet, basename='transaction')
router.register(r'cashflow/saving', views.SavingViewSet, basename='saving')


app_name = 'cashflow'
urlpatterns = [
    path('saving/', views.saving, name='saving'),
    path('transaction/', views.transaction, name='transaction'),
    path('', views.dashboard, name='dashboard'),
]

goodblog/blog/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy
from django.template.defaultfilters import slugify

from tinymce.models import HTMLField
from taggit.managers import TaggableManager


class UserProfile(models.Model):
    USER_LEVEL_OPTIONS = [
        (1, 'Administrator'),
        (2, 'Author'),
        (3, 'Reader'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE, editable=False)
    level = models.SmallIntegerField(choices=USER_LEVEL_OPTIONS, default=3)

    def __str__(self):
        return str(self.level)


class Post(models.Model):
    title = models.CharField(max_length=255, unique=True)
    create_date = models.DateTimeField(auto_now_add=True)
    publish_date = models.DateTimeField(null=True, blank=True, help_text="yyyy-mm-dd hh:mm:ss")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = TaggableManager()
    content = HTMLField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('blog:post-detail', args=[self.id, slugify(self.title)])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    publish_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = HTMLField()

    def __str__(self):
        return self.publish_date.strftime("%d %B %Y, %H:%M")

goodblog/djcore/models.py
from django.contrib.sites.models import Site
from django.db import models
from django.utils.translation import gettext_lazy as _


class SiteConfig(models.Model):
    site = models.OneToOneField(Site, on_delete=models.CASCADE)
    home_page_title = models.CharField(max_length=128, null=True, blank=True)
    show_intro_menu = models.BooleanField(default=False)

    def __str__(self):
        return self.home_page_title

    def save(self, *args, **kwargs):
        Site.objects.clear_cache()
        super(SiteConfig, self).save(*args, **kwargs)


class Core(models.Model):
    name = models.CharField(max_length=128, default='GoodBlog')
    slogan = models.CharField(max_length=128, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    detail = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Contact(models.Model):

    class ContactType(models.TextChoices):
        EMAIL = 'email', _('Email')
        PHONE = 'phone', _('Phone')
        FAX = 'fax', _('Fax')
        MOBILE_PHONE = 'mobile', _('Mobile Phone')

    name = models.CharField(max_length=16, choices=ContactType.choices, null=True, blank=True)
    content = models.CharField(max_length=64)
    core = models.ForeignKey(Core, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name


class Service(models.Model):
    name = models.CharField(max_length=64)
    overview = models.TextField(null=True, blank=True)
    detail = models.TextField(null=True, blank=True)
    core = models.ForeignKey(Core, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name


class Portfolio(models.Model):
    name = models.CharField(max_length=128)
    webpage = models.URLField(null=True, blank=True)
    overview = models.TextField(null=True, blank=True)
    detail = models.TextField(null=True, blank=True)
    core = models.ForeignKey(Core, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

goodblog/djcore/forms.py
from allauth.account import forms
from captcha.fields import CaptchaField


class DjcoreLoginForm(forms.LoginForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget.attrs.update({'class': 'input is-rounded is-medium'})
        self.fields['login'].widget.attrs.update({'class': 'input is-rounded is-medium'})
        self.fields['remember'].widget.attrs.update({'class': 'checkbox'})


class DjcoreSignupForm(forms.SignupForm):
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'input'})
        self.fields['email'].widget.attrs.update({'class': 'input'})
        self.fields['captcha'].widget.attrs.update({'class': 'input'})
        self.fields['password1'].widget.attrs.update({'class': 'input'})
        self.fields['password2'].widget.attrs.update({'class': 'input'})


class DjcoreAddEmailForm(forms.AddEmailForm):
    def __init__(self, user=None, *args, **kwargs):
        super().__init__(user=user, *args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'input'})


class DjcoreChangePasswordForm(forms.ChangePasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['oldpassword'].widget.attrs.update({'class': 'input'})
        self.fields['password1'].widget.attrs.update({'class': 'input'})
        self.fields['password2'].widget.attrs.update({'class': 'input'})


class DjcoreResetPasswordForm(forms.ResetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'input'})


class DjcoreResetPasswordKeyForm(forms.ResetPasswordKeyForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.update({'class': 'input'})
        self.fields['password2'].widget.attrs.update({'class': 'input'})

goodblog/djcore/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Prefetch
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.utils import timezone

from taggit.models import Tag

from blog.models import Post
from djcore.models import Core


@method_decorator(login_required, name='dispatch')
class UserDetail(DetailView):
    model = User
    slug_field = 'username'
    template_name = 'djcore/user-detail.html'


def intro(request):
    core = Core.objects.prefetch_related(
            Prefetch('contact_set')).prefetch_related(
                    Prefetch('service_set')).prefetch_related(
                            Prefetch('portfolio_set')).first()
    return render(request, 'djcore/intro.html', {'core': core})


class HomePage(ListView):
    model = Post
    paginate_by = 7
    template_name = 'blog/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context

    def get_queryset(self):
        return self.model.objects.filter(publish_date__lte=timezone.now()).select_related('author'
            ).prefetch_related('tags').order_by('-publish_date')[:7]

goodblog/djcore/templates/djcore/base.html
<!doctype html>
{% load static %}
<html lang="id">
<head>
    <meta charset="utf-8">
    <link rel="icon" href="{% static 'djcore/img/favicon.ico' %}" type="image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Personal website of Ikhsan Noor Rosyidin.">
    <title>{% block page_title %}{{ request.site.siteconfig.home_page_title }}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'vendor/bulma/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/fontawesome/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/flatpickr/flatpickr.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/goodblog.css' %}">

    {% block extra_head %}{% endblock %}
</head>
<body>
    <nav class="navbar is-info is-boxed" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="https://{{ request.site }}">
                <p class="title">{{ request.site.name }}</p>
            </a>

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
                data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                {% if request.site.siteconfig.show_intro_menu %}
                    <a class="navbar-item" href="{% url 'intro' %}">Intro</a>
                {% endif %}
                <a class="navbar-item" href="{% url 'home' %}">Beranda</a>
                {% if request.user.is_authenticated %}
                    {% if request.user.userprofile.level < 3 %}
                    <a class="navbar-item" href="{% url 'blog:user-posts' %}">Tulisanku</a>
                    {% endif %}
                    <a class="navbar-item" href="{% url 'cashflow:dashboard' %}">Keuangan</a>
                {% endif %}
            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    {% if request.user.is_authenticated %}
                    <div class="buttons">
                        <a class="button is-primary" href="{% url 'user_profile' slug=request.user.username %}">
                            <strong>{{ request.user }}</strong>
                        </a>
                        <button class="button is-warning is-light modal-button" data-target="logoutmodal" aria-haspopup="true">Keluar</button>
                    </div>
                    {% else %}
                    <div class="buttons">
                        <a class="button is-primary" href="{% url 'account_signup' %}">
                            <strong>Daftar</strong>
                        </a>
                        <a class="button is-primary" href="{% url 'account_login' %}">
                            <strong>Masuk</strong>
                        </a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <section class="section">
        <div class="columns">
            <div class="column is-one-quarter">
                {% block side_menu %}{% endblock %}
            </div>
            <div class="column">
                {% block page_content %}{% endblock %}
            </div>
        </div>
    </section>
    <section class="section">
        <footer class="footer">
            <div class="content has-text-centered">
                <p>
                    <strong>Pupil</strong> adalah <a href="https://twitter.com/essanpupil" target="_blank">Ikhsan N. Rosyidin</a>.
                    Lisensi kode sumber adalah <a href="http://opensource.org/licenses/mit-license.php" target="_blank">MIT</a>.
                    Lisensi konten website adalah <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY NC SA 4.0</a>.
                    Repository kode sumber ada di <a href="https://gitlab.com/essanpupil/goodblog" target="_blank">Gitlab</a>.
                </p>
            </div>
        </footer>
    </section>
    <div id="logoutmodal" class="modal">
        <div class="modal-background"></div>
        <div class="modal-card">
            <header class="modal-card-head">
              <p class="modal-card-title">Apakah anda yakin ingin keluar?</p>
              <button class="delete" aria-label="close"></button>
            </header>
            <section class="modal-card-body">
                <form method="post" action="{% url 'account_logout' %}">
                    {% csrf_token %}
                    {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                    {% endif %}
                    <button class="button is-danger" type="submit">Keluar</button>
                  </form>
            </section>
        </div>
        <button class="modal-close is-large" aria-label="close"></button>
    </div>
    <script defer src="{% static 'js/goodblog.js' %}"></script>
    <script defer src="{% static 'vendor/flatpickr/flatpickr.min.js' %}"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

goodblog/djcore/templates/djcore/djcore-base.html
{% extends 'djcore/base.html' %}

{% block side_menu %}
<div class="dropdown is-hidden-desktop">
    <div class="dropdown-trigger">
        <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
            <span>Pengaturanku</span>
            <span class="icon is-small">
                <i class="fa fa-angle-down" aria-hidden="true"></i>
            </span>
        </button>
    </div>
    <div class="dropdown-menu" id="dropdown-menu" role="menu">
        <div class="dropdown-content">
            <a href="{% url 'user_profile' request.user.username %}" class="dropdown-item">
                Profile
            </a>
            <a href="{% url 'account_email' %}" class="dropdown-item">
                Email
            </a>
            <a href="{% url 'account_change_password' %}" class="dropdown-item">
                Ubah kata sandi
            </a>
        </div>
    </div>
</div>

<aside class="menu is-hidden-touch">
    <p class="menu-label">Pengaturan</p>
    <ul class="menu-list">
        <li><a href="{% url 'user_profile' request.user.username %}">Profile</a></li>
        <li><a href="{% url 'account_email' %}">Email</a></li>
        <li><a href="{% url 'account_change_password' %}">Ubah kata sandi</a></li>
    </ul>
</aside>
{% endblock %}

goodblog/djcore/templates/djcore/intro.html
{% extends 'djcore/base.html' %}

{% block side_menu %}
{% if core.contact_set.count %}
<div class="dropdown is-hidden-desktop">
    <div class="dropdown-trigger">
        <button class="button" aria-haspopup="true" aria-controls="dropdown-contact">
            <span>Kontak</span>
            <span class="icon is-small">
                <i class="fa fa-angle-down" aria-hidden="true"></i>
            </span>
        </button>
    </div>
    <div class="dropdown-menu" id="dropdown-contact" role="menu">
        <div class="dropdown-content">
            {% for contact in core.contact_set.all %}
                {% if contact.name == 'email' %}
                <a href="mailto:{{ contact.content }}" class="dropdown-item">
                    {{ contact.content }}
                </a>
                {% else %}
                <div class="dropdown-item">
                    {{ contact.name }}: {{ contact.content }}
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}

{% if core.address %}
<div class="dropdown is-hidden-desktop">
    <div class="dropdown-trigger">
        <button class="button" aria-haspopup="true" aria-controls="dropdown-address">
            <span>Alamat</span>
            <span class="icon is-small">
                <i class="fa fa-angle-down" aria-hidden="true"></i>
            </span>
        </button>
    </div>
    <div class="dropdown-menu" id="dropdown-address" role="menu">
        <div class="dropdown-content">
            <p>{{ core.address }}</p>
        </div>
    </div>
</div>
{% endif %}

<aside class="menu is-hidden-touch">
    {% if core.contact_set.count %}
    <p class="menu-label">Kontak</p>
    <ul class="menu-list">
        {% for contact in core.contact_set.all %}
            {% if contact.name == 'email' %}
                <li><a href="mailto:{{ contact.content }}">{{ contact.content }}</a></li>
            {% else %}
                <li><strong>{{ contact.name }}</strong>: {{ contact.content }}</li>
            {% endif %}
        {% endfor %}
    </ul>
    {% endif %}

    {% if core.address %}
    <p class="menu-label">Alamat</p>
    <ul class="menu-list">
        <li>{{ core.address }}</li>
    </ul>
    {% endif %}
</aside>

{% endblock %}

{% block page_content %}
    <h1 class="title">{{ core.name }}</h1>
    <h2 class="subtitle">{{ core.slogan }}</h2>
    <div class="content">
        {{ core.detail }}
    </div>

    <div class="columns">
    {% if core.service_set.count %}
        <div class="column">
            <p class="title">Servis</p>
            <div class="content">
            <ul>
            {% for service in core.service_set.all %}
            <li>{{ service.name }}</li>
            {% endfor %}
            </ul>
            </div>
        </div>
    {% endif %}

    {% if core.portfolio_set.count %}
        <div class="column">
            <p class="title">Portfolio</p>
            <div class="content">
            <ul>
            {% for portfolio in core.portfolio_set.all %}
            <li>{{ portfolio.name }}</li>
            {% endfor %}
            </ul>
            </div>
        </div>
    {% endif %}
    </div>
{% endblock %}

goodblog/djcore/templates/djcore/user-detail.html
{% extends "djcore/djcore-base.html" %}

{% load account socialaccount %}

{% block page_content %}
<div class="content">
    <h1>{{ object.get_full_name }}</h1>
    <table class="table is-hoverable">
        <tr><th>Username</th><td>{{ object.username }}</td></tr>
        <tr><th>Email</th><td>{{ object.email }}</td></tr>
        <tr><th>Level</th><td>{{ object.userprofile.get_level_display }}</td></tr>
    </table>
</div>
{% endblock %}