goodblog/blog/urls.py
from django.urls import path

from goodblog.urls import router
from . import views


router.register(r'blog/articles', views.PostViewSet)

app_name='blog'
urlpatterns = [
    path('new-post/', views.PostView.as_view(), name='new-post'),
    path('my-posts/', views.MyPostsView.as_view(), name='user-posts'),
    path('search/', views.SearchPostView.as_view(), name='search-post'),
    path('tag/<tag_name>', views.tag_posts, name='tag-posts'),
    path('article/<pk>/<slug:title>', views.PostDetail.as_view(), name='post-detail'),
    path('update-article/<pk>', views.PostUpdate.as_view(), name='post-update'),
    path('publish-article/<post_id>', views.publish_post, name='publish-post'),
    path('unpublish-article/<post_id>', views.unpublish_post, name='unpublish-post'),
]

goodblog/cashflow/urls.py
from django.urls import path

from goodblog.urls import router

from . import views

router.register(r'cashflow/transaction', views.TransactionViewSet, basename='transaction')
router.register(r'cashflow/saving', views.SavingViewSet, basename='saving')


app_name = 'cashflow'
urlpatterns = [
    path('saving/', views.saving, name='saving'),
    path('transaction/', views.transaction, name='transaction'),
    path('', views.dashboard, name='dashboard'),
]

goodblog/cashflow/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models

from djmoney.models.fields import MoneyField


class Saving(models.Model):
    name = models.CharField(max_length=64)
    balance = MoneyField(max_digits=10, default_currency='IDR')
    description = models.TextField(blank=True, null=True)
    is_default = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.is_default:
            try:
                current_default = Saving.objects.get(owner=self.owner, is_default=True)
                current_default.is_default=False
                current_default.save()
            except Saving.DoesNotExist:
                self.is_default = True
            super(Saving, self).save(*args, **kwargs)
        else:
            try:
                current_default = Saving.objects.get(owner=self.owner, is_default=True)
            except Saving.DoesNotExist:
                self.is_default=True
            super(Saving, self).save(*args, **kwargs)


class Transaction(models.Model):
    TRANSACTION_CHOICES = [
        ('in', 'Income'),
        ('out', 'Expense'),
    ]
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    description = models.CharField(max_length=255)
    date = models.DateField()
    transaction_type = models.CharField(max_length=3, choices=TRANSACTION_CHOICES, default='out')
    amount = MoneyField(max_digits=9, default_currency='IDR')
    entry_by = models.ForeignKey(User, on_delete=models.CASCADE)
    saving = models.ForeignKey(Saving, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.description

    def save(self, *args, **kwargs):
        try:
            old_transaction = Transaction.objects.get(id=self.id)
            if self.saving is None and old_transaction.saving is not None:
                if self.transaction_type == 'in':
                    old_transaction.saving.balance = models.F('balance') - old_transaction.amount
                if self.transaction_type == 'out':
                    old_transaction.saving.balance = models.F('balance') + old_transaction.amount
                old_transaction.saving.save()
                super(Transaction, self).save(*args, **kwargs)

            if self.saving is not None and old_transaction.saving is not None:
                if self.saving.owner == self.entry_by and self.transaction_type == 'out':
                    old_transaction.saving.balance = models.F('balance') + old_transaction.amount
                    old_transaction.saving.save()
                    self.saving.balance = models.F('balance') - self.amount
                elif self.saving.owner == self.entry_by and self.transaction_type == 'in':
                    old_transaction.saving.balance = models.F('balance') - old_transaction.amount
                    old_transaction.saving.save()
                    self.saving.balance = models.F('balance') + self.amount
                else:
                    raise ValueError('Saving is not owned by user')
                self.saving.save()
                super(Transaction, self).save(*args, **kwargs)

        except Transaction.DoesNotExist:
            if self.saving is None:
                super(Transaction, self).save(*args, **kwargs)
            else:
                if self.saving.owner == self.entry_by and self.transaction_type == 'out':
                    self.saving.balance = models.F('balance') - self.amount
                elif self.saving.owner == self.entry_by and self.transaction_type == 'in':
                    self.saving.balance = models.F('balance') + self.amount
                else:
                    raise ValueError('Saving is not owned by user')
                self.saving.save()
                super(Transaction, self).save(*args, **kwargs)

goodblog/cashflow/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from rest_framework.viewsets import ModelViewSet
from django_filters.rest_framework import DjangoFilterBackend

from . import models, serializers, permissions, filters

@login_required
def dashboard(request):
    return render(request, 'cashflow/dashboard.html')


@login_required
def transaction(request):
    return render(request, 'cashflow/transaction.html')


@login_required
def saving(request):
    return render(request, 'cashflow/saving.html')


class SavingViewSet(ModelViewSet):
    serializer_class = serializers.SavingSerializer
    permission_classes = (
        permissions.SavingAccessPolicy,
    )

    def get_queryset(self):
        return models.Saving.objects.filter(owner=self.request.user).order_by('-id')

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)


class TransactionViewSet(ModelViewSet):
    filter_backends = [DjangoFilterBackend]
    filterset_class = filters.TransactionFilter
    serializer_class = serializers.TransactionSerializer
    permission_classes = (
        permissions.TransactionAccessPolicy,
    )

    def get_queryset(self):
        return models.Transaction.objects.filter(
            entry_by=self.request.user).order_by('-date', '-id')

    def perform_create(self, serializer):
        serializer.save(entry_by=self.request.user)

goodblog/cashflow/templates/cashflow/dashboard.html
{% extends 'djcore/base.html' %}

{% block side_menu %}
{% include 'cashflow/side-menu.html' %}
{% endblock %}

{% block page_content %}
<h1 class="title">Keuangan</h1>
{% endblock %}

goodblog/cashflow/templates/cashflow/saving.html
{% extends 'djcore/base.html' %}
{% load static %}

{% block side_menu %}
{% include 'cashflow/side-menu.html' %}
{% endblock %}

{% block page_content %}
<div class="box">
    <h1 class="subtitle">Form tambah simpanan</h1>
    <form id="saving-form" class ="form" method="POST">{% csrf_token %}
        <div class="field is-horizontal">
            <div class="field-label">
                <label class="label">Nama</label>
            </div>
            <div class="field-body">
                <div class="field">
                    <div class="control is-expanded">
                        <input id="id_name" type="text" class="input" placeholder="Nama akun simpanan">
                    </div>
                </div>
            </div>
        </div>
        <div class="field is-horizontal">
            <div class="field-label">
                <label class="label">Saldo</label>
            </div>
            <div class="field-body">
                <div class="field has-addons">
                    <div class="control">
                        <div class="select">
                            <select id="id_currency" name="currency">
                                <option value='IDR'>Rp</option>
                            </select>
                        </div>
                    </div>
                    <div class="control">
                        <input id="id_amount" type="number" class="input" placeholder="Saldo">
                    </div>
                </div>
                <div class="field">
                    <label class="checkbox">
                        <input id="id_is_default" type="checkbox">Jadikan simpanan utama
                    </label>
                </div>
            </div>
        </div>
        <div class="field">
            <textarea id="id_description" class="textarea" placeholder="Keterangan"></textarea>
        </div>
        <button class="button is-primary">Simpan</button>
        <button class="button is-warning is-light">Reset</button>
    </form>
</div>

<div class="box">
    <h1 class="subtitle">Akun simpanan terbaru</h1>
    <table id="saving-table" class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
        <thead><tr><th>No.</th><th>Nama</th><th>Simpanan Utama</th><th>Mata Uang</th><th>Saldo</th><th>Alat</th></thead>
        <tbody><tr><td> - </td><td> - </td><td> - </td><td> - </td><td> - </td><td> - </td></tbody>
        <tfoot><tr><th>No.</th><th>Nama</th><th>Simpanan Utama</th><th>Mata Uang</th><th>Saldo</th><th>Alat</th></tfoot>
    </table>
</div>
{% endblock %}

{% block extra_js %}
<script defer type="text/javascript" src="{% static 'cashflow/js/saving.js' %}"></script>
{% endblock %}

goodblog/cashflow/templates/cashflow/side-menu.html
<div class="box">
    <div class="dropdown is-hidden-desktop">
        <div class="dropdown-trigger">
            <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
                <span>Atur Keuangan</span>
                <span class="icon is-small">
                    <i class="fa fa-angle-down" aria-hidden="true"></i>
                </span>
            </button>
        </div>
        <div class="dropdown-menu" id="dropdown-menu" role="menu">
            <div class="dropdown-content">
                <a href="{% url 'cashflow:dashboard' %}" class="dropdown-item">
                    Dashboard
                </a>
                <a href="{% url 'cashflow:transaction' %}" class="dropdown-item">
                    Transaksi
                </a>
                <a href="{% url 'cashflow:saving' %}" class="dropdown-item">
                    Simpanan
                </a>
            </div>
        </div>
    </div>

    <aside class="menu is-hidden-touch">
        <p class="menu-label">
            Atur Keuangan
        </p>
        <ul class="menu-list">
            <li><a href="{% url 'cashflow:dashboard' %}">Dashboard</a></li>
            <li><a href="{% url 'cashflow:transaction' %}">Transaksi</a></li>
            <li><a href="{% url 'cashflow:saving' %}">Simpanan</a></li>
        </ul>
    </aside>
</div>

goodblog/cashflow/templates/cashflow/transaction.html
{% extends 'djcore/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'blog/vendor/flatpickr/plugins/confirmDate.css' %}">
{% endblock %}

{% block side_menu %}
{% include 'cashflow/side-menu.html' %}
{% endblock %}

{% block page_content %}
<div class="box">
    <form id="transaction-form" name="cash-form" method="POST">{% csrf_token %}
        <div class="field is-horizontal">
            <div class="field-label">
                <label class="label">Keterangan</label>
            </div>
            <div class="field-body">
                <div class="field has-addons">
                    <p class="control is-expanded">
                        <input id="id_description" class="input" type="text" placeholder="Keterangan" />
                    </p>
                    <p class="control has-icons-right">
                        <input id="id_date" name="date" class="input transaction_time" type="text" placeholder="Tanggal" />
                        <span class="icon is-right">
                            <em class="fa fa-calendar"></em>
                        </span>
                    </p>
                </div>
            </div>
        </div>
        <div class="field is-horizontal">
            <div class="field-label">
                <label class="label">Jumlah</label>
            </div>
            <div class="field-body">
                <div class="field has-addons">
                    <p class="control">
                        <span class="select">
                            <select id="id_currency" name="amount_currency">
                                <option value="IDR">Rupiah</option>
                            </select>
                        </span>
                    </p>
                    <p class="control">
                        <input id="id_amount" class="input" type="number" placeholder="Jumlah" />
                    </p>
                </div>
            </div>
        </div>
        <div class="field is-horizontal">
            <div class="field-label">
                <label class="label">Simpanan</label>
            </div>
            <div class="field-body">
                <div class="field has-addons">
                    <p class="control">
                        <span class="select">
                            <select id="id_saving" class="savingSelect" name="saving">
                                <option value="" selected>Pilih sumber simpanan</option>
                            </select>
                        </span>
                    </p>
                    <p class="control">
                        <span class="select">
                            <select id="id_transaction_type" name="transaction_type">
                                <option value="out">Keluar</option>
                                <option value="in">Masuk</option>
                            </select>
                        </span>
                    </p>
                </div>
                <button id="saveTransactionButton" type="submit" class="button is-primary">Simpan</button>
                <button type="reset" class="button is-warning is-light">Reset</button>
            </div>
        </div>
    </form>
</div>

<div class="box">
    <nav class="pagination is-small is-rounded" role="navigation" aria-label="pagination">
        <a id="previous-button" class="pagination-previous">Balik</a>
        <a id="next-button" class="pagination-next">Lanjut</a>
    </nav>
    <form id="filter-form">
        <div class="field is-horizontal">
            <div class="field-body">
                <div class="field">
                    <p class="control has-icons-left">
                        <input id="time-filter" class="input transaction_time" type="text" placeholder="Tanggal" />
                        <span class="icon is-left">
                            <em class="fa fa-calendar"></em>
                        </span>
                    </p>
                </div>
                <div class="field">
                    <p class="control">
                        <input id="description-filter" class="input" type="text" placeholder="Keterangan" />
                    </p>
                </div>
                <div class="field">
                    <p class="control">
                        <span class="select">
                            <select id="type-filter" name="transaction_type">
                                <option value="out">Keluar</option>
                                <option value="in">Masuk</option>
                            </select>
                        </span>
                    </p>
                </div>
                <div class="field">
                    <p class="control">
                        <span class="select">
                            <select id="saving-filter" class="savingSelect" name="saving">
                                <option value="" selected>Pilih sumber simpanan</option>
                            </select>
                        </span>
                    </p>
                </div>
                <div class="field">
                    <button id="filterTransaction" type="submit" class="button is-primary">Filter</button>
                </div>
                <div class="field">
                    <button id="resetFilter" type="reset" class="button is-warning is-light">Reset</button>
                </div>
            </div>
        </div>
    </form>
    <br />
    <table id="transaction-table" class="table is-narrow is-bordered is-striped is-fullwidth">
        <thead>
            <tr>
                <th scope="col">Waktu</th>
                <th scope="col">Keterangan</th>
                <th scope="col">Jumlah</th>
                <th scope="col">Simpanan</th>
                <th scope="col">Alat</th>
            </tr>
        </thead>
        <tbody>
            <tr><td> - </td><td> - </td><td> - </td><td> - </td><td> - </td></tr>
        </tbody>
    </table>
</div>
{% endblock %}

{% block extra_js %}
<script defer type="text/javascript" src="{% static 'vendor/flatpickr/plugins/confirmDate.js' %}"></script>
<script defer type="text/javascript" src="{% static 'cashflow/js/transaction.js' %}"></script>
{% endblock %}